image:
- Visual Studio 2017
- Ubuntu

before_build:
- nuget restore src

build:
  project: src

configuration:
- Release

test:

for:
-
  matrix:
    only:
    - image: Ubuntu

  test_script:
  - mono ~/.nuget/packages/xunit.runner.console/2.4.1/tools/net472/xunit.console.exe src/DemoLib.Tests/bin/Release/net472/DemoLib.Tests.dll
